// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1alpha1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using CacheSpec within kubernetes types, where deepcopy-gen is used.
func (in *CacheSpec) DeepCopyInto(out *CacheSpec) {
	p := proto.Clone(in).(*CacheSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheSpec. Required by controller-gen.
func (in *CacheSpec) DeepCopy() *CacheSpec {
	if in == nil {
		return nil
	}
	out := new(CacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CacheSpec. Required by controller-gen.
func (in *CacheSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DataSourceSpec within kubernetes types, where deepcopy-gen is used.
func (in *DataSourceSpec) DeepCopyInto(out *DataSourceSpec) {
	p := proto.Clone(in).(*DataSourceSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpec. Required by controller-gen.
func (in *DataSourceSpec) DeepCopy() *DataSourceSpec {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpec. Required by controller-gen.
func (in *DataSourceSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using EagerCachingRuleSpec within kubernetes types, where deepcopy-gen is used.
func (in *EagerCachingRuleSpec) DeepCopyInto(out *EagerCachingRuleSpec) {
	p := proto.Clone(in).(*EagerCachingRuleSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EagerCachingRuleSpec. Required by controller-gen.
func (in *EagerCachingRuleSpec) DeepCopy() *EagerCachingRuleSpec {
	if in == nil {
		return nil
	}
	out := new(EagerCachingRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new EagerCachingRuleSpec. Required by controller-gen.
func (in *EagerCachingRuleSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using LazyCachingRuleSpec within kubernetes types, where deepcopy-gen is used.
func (in *LazyCachingRuleSpec) DeepCopyInto(out *LazyCachingRuleSpec) {
	p := proto.Clone(in).(*LazyCachingRuleSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LazyCachingRuleSpec. Required by controller-gen.
func (in *LazyCachingRuleSpec) DeepCopy() *LazyCachingRuleSpec {
	if in == nil {
		return nil
	}
	out := new(LazyCachingRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LazyCachingRuleSpec. Required by controller-gen.
func (in *LazyCachingRuleSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NamespacedRef within kubernetes types, where deepcopy-gen is used.
func (in *NamespacedRef) DeepCopyInto(out *NamespacedRef) {
	p := proto.Clone(in).(*NamespacedRef)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedRef. Required by controller-gen.
func (in *NamespacedRef) DeepCopy() *NamespacedRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedRef. Required by controller-gen.
func (in *NamespacedRef) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CacheConf within kubernetes types, where deepcopy-gen is used.
func (in *CacheConf) DeepCopyInto(out *CacheConf) {
	p := proto.Clone(in).(*CacheConf)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheConf. Required by controller-gen.
func (in *CacheConf) DeepCopy() *CacheConf {
	if in == nil {
		return nil
	}
	out := new(CacheConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CacheConf. Required by controller-gen.
func (in *CacheConf) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
